-- ============================================================
-- Website Analytics — first-party tracking, intake funnel, SEO
--
-- Answers three questions for the Social Media module:
--   1. How are people finding us?            (acquisition + SEO)
--   2. What are they doing on the website?   (behaviour)
--   3. Are they becoming qualified leads?    (intake funnel + conversion)
--
-- Data flow
--   public/sdfm-tracker.js  ──►  track_web_batch()  ──►  web_sessions / web_events
--   sm-gsc-sync (Edge Fn)   ──►  seo_* tables (Google Search Console API)
--   web_analytics_* / seo_overview()  ──►  read by /social/website-analytics
--
-- Privacy model ("hybrid consent")
--   - Anonymous sessions are always counted: no IP address is stored, no
--     persistent ID is set, and query strings other than utm_* are dropped.
--   - visitor_id is only stored when the visitor accepted cookies
--     (consented = true). It powers returning-visitor counts only.
--
-- Security
--   - The tracker tables have RLS enabled and NO insert/update policies:
--     the only write path is track_web_batch() (SECURITY DEFINER), which
--     validates and caps everything it accepts. Anon cannot touch the
--     tables directly.
--   - Reads are limited to the admin/marketing roles, matching the rest of
--     the Social Media module. The reporting functions re-check the role
--     themselves because they are SECURITY DEFINER.
--
-- Run this in the Supabase SQL Editor (all at once), after schema.sql and
-- migration-social-media.sql. Safe to re-run.
-- IMPORTANT: run this BEFORE deploying the frontend that loads the tracker.
-- ============================================================


-- 0. Role helper ------------------------------------------------------------
create or replace function public.wa_is_content_team()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('admin', 'marketing')
  );
$$;


-- 1. Sessions ---------------------------------------------------------------
-- id is generated by the browser so a session can be continued across the
-- marketing site and the intake form (cross-domain link decoration).
create table if not exists public.web_sessions (
  id uuid primary key,
  visitor_id text,                      -- only when consented
  consented boolean not null default false,
  is_returning boolean not null default false,

  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),

  -- First-touch attribution (written once, when the session is created)
  host text,
  landing_path text,
  referrer text,
  referrer_domain text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  source text,                          -- normalised: google, linkedin, ...
  medium text,                          -- normalised: organic, social, ...
  channel text not null default 'Direct',

  -- Environment (no IP, no precise location)
  device_type text,
  browser text,
  os text,
  language text,
  timezone text,
  viewport_w integer,

  -- Rolled up by track_web_batch()
  pageviews integer not null default 0,
  event_count integer not null default 0,
  engaged_ms bigint not null default 0,
  max_scroll integer not null default 0,

  -- Set when the intake form creates a lead from this session
  lead_id uuid
);

create index if not exists web_sessions_started_idx on public.web_sessions (started_at);
create index if not exists web_sessions_channel_idx on public.web_sessions (channel, started_at);
create index if not exists web_sessions_lead_idx on public.web_sessions (lead_id) where lead_id is not null;

alter table public.web_sessions enable row level security;

drop policy if exists "Content team can view web sessions" on public.web_sessions;
create policy "Content team can view web sessions"
  on public.web_sessions for select
  to authenticated
  using (public.wa_is_content_team());


-- 2. Events -----------------------------------------------------------------
create table if not exists public.web_events (
  id bigint generated always as identity primary key,
  session_id uuid not null references public.web_sessions(id) on delete cascade,
  eid text not null,                    -- client event id, makes retries idempotent
  occurred_at timestamptz not null default now(),
  type text not null,                   -- pageview, page_leave, click, form_*, ...
  host text,
  path text,
  title text,
  props jsonb not null default '{}'::jsonb
);

create unique index if not exists web_events_session_eid_idx on public.web_events (session_id, eid);
create index if not exists web_events_type_time_idx on public.web_events (type, occurred_at);
create index if not exists web_events_time_idx on public.web_events (occurred_at);

alter table public.web_events enable row level security;

drop policy if exists "Content team can view web events" on public.web_events;
create policy "Content team can view web events"
  on public.web_events for select
  to authenticated
  using (public.wa_is_content_team());


-- 3. Traffic classification -------------------------------------------------
-- Turns utm_source / utm_medium / referrer domain into a clean source,
-- medium and channel. First-touch only (called when a session is created).
create or replace function public.wa_classify_traffic(p_source text, p_medium text, p_referrer_domain text)
returns table (source text, medium text, channel text)
language plpgsql
immutable
as $$
declare
  v_s text := lower(nullif(btrim(coalesce(p_source, '')), ''));
  v_m text := lower(nullif(btrim(coalesce(p_medium, '')), ''));
  v_d text := regexp_replace(lower(coalesce(p_referrer_domain, '')), '^www\.', '');
  v_search boolean;
  v_social boolean;
  v_email boolean;
  v_paid boolean;
  v_c text;
begin
  -- Name the source from the referrer when no utm_source was supplied.
  if v_s is null and v_d <> '' then
    v_s := case
      when v_d = 'mail.google.com' then 'gmail'
      when v_d in ('outlook.live.com', 'outlook.office.com', 'outlook.office365.com') then 'outlook'
      when v_d ~ '^google\.[a-z.]+$' then 'google'
      when v_d ~ '(^|\.)bing\.com$' then 'bing'
      when v_d ~ '(^|\.)duckduckgo\.com$' then 'duckduckgo'
      when v_d ~ '(^|\.)yahoo\.com$' then 'yahoo'
      when v_d ~ '^yandex\.' then 'yandex'
      when v_d ~ '(^|\.)baidu\.com$' then 'baidu'
      when v_d ~ '(^|\.)ecosia\.org$' then 'ecosia'
      when v_d = 'search.brave.com' then 'brave'
      when v_d ~ '(^|\.)linkedin\.com$' or v_d = 'lnkd.in' then 'linkedin'
      when v_d ~ '(^|\.)(facebook|fb)\.com$' then 'facebook'
      when v_d ~ '(^|\.)instagram\.com$' then 'instagram'
      when v_d in ('t.co', 'x.com', 'twitter.com') or v_d ~ '\.(x|twitter)\.com$' then 'twitter'
      when v_d ~ '(^|\.)youtube\.com$' or v_d = 'youtu.be' then 'youtube'
      when v_d ~ '(^|\.)whatsapp\.com$' or v_d = 'wa.me' then 'whatsapp'
      when v_d ~ '(^|\.)tiktok\.com$' then 'tiktok'
      when v_d ~ '(^|\.)reddit\.com$' then 'reddit'
      when v_d ~ '(^|\.)pinterest\.' then 'pinterest'
      else v_d
    end;
  end if;

  -- Fold common utm_source aliases onto the same names.
  if v_s is not null then
    v_s := case
      when v_s in ('li', 'lnkd.in', 'linkedin.com') then 'linkedin'
      when v_s in ('fb', 'facebook.com') then 'facebook'
      when v_s in ('ig', 'instagram.com') then 'instagram'
      when v_s in ('x', 't.co', 'twitter.com', 'x.com') then 'twitter'
      when v_s in ('google.com') then 'google'
      else v_s
    end;
  end if;

  v_search := v_s in ('google', 'bing', 'duckduckgo', 'yahoo', 'yandex', 'baidu', 'ecosia', 'brave');
  v_social := v_s in ('linkedin', 'facebook', 'instagram', 'twitter', 'youtube', 'whatsapp', 'tiktok', 'reddit', 'pinterest', 'threads');
  v_email := v_s in ('gmail', 'outlook') or v_m in ('email', 'e-mail', 'newsletter', 'mail');
  v_paid := coalesce(v_m ~ '^(cpc|ppc|cpm|cpv|cpa|display|retargeting|sponsored|paid.*)$', false);

  -- Medium comes from the referrer when there was no utm_medium.
  if v_m is null and v_d <> '' then
    v_m := case
      when v_search then 'organic'
      when v_social then 'social'
      when v_s in ('gmail', 'outlook') then 'email'
      else 'referral'
    end;
  end if;

  v_c := case
    when v_paid and v_social then 'Paid Social'
    when v_paid and v_search then 'Paid Search'
    when v_paid then 'Paid Other'
    when v_email then 'Email'
    when v_social or v_m in ('social', 'social-media', 'social_media') then 'Social'
    when v_search or v_m = 'organic' then 'Organic Search'
    when v_m = 'referral' then 'Referral'
    when v_s is null and v_m is null then 'Direct'
    else 'Other'
  end;

  return query select v_s, v_m, v_c;
end;
$$;


-- 4. Tracker ingest ---------------------------------------------------------
-- The only write path into web_sessions / web_events. Called by the browser
-- tracker with the public anon key, so it assumes hostile input: it caps
-- batch and per-session sizes, whitelists the shape of every field, ignores
-- obvious crawlers, and never trusts client clocks (events carry age_ms).
create or replace function public.track_web_batch(payload jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_headers json;
  v_ua text;
  s jsonb;
  v_events jsonb;
  v_sid uuid;
  v_visitor text;
  v_consented boolean;
  v_ref text;
  v_ref_domain text;
  v_cls record;
  v_existing int;
  v_n int := 0;
  v_pv int := 0;
  v_engaged bigint := 0;
  v_scroll int := 0;
  v_lead_txt text;
  v_lead uuid;
begin
  -- Crawlers and link-preview fetchers are not visitors.
  begin
    v_headers := nullif(current_setting('request.headers', true), '')::json;
  exception when others then
    v_headers := null;
  end;
  v_ua := coalesce(v_headers ->> 'user-agent', '');
  if v_ua ~* '(bot|crawler|spider|slurp|headless|lighthouse|pagespeed|facebookexternalhit)' then
    return;
  end if;

  if payload is null or jsonb_typeof(payload) <> 'object' then return; end if;
  s := payload -> 'session';
  if s is null or jsonb_typeof(s) <> 'object' then return; end if;

  begin
    v_sid := (s ->> 'id')::uuid;
  exception when others then
    return;
  end;
  if v_sid is null then return; end if;

  v_events := coalesce(payload -> 'events', '[]'::jsonb);
  if jsonb_typeof(v_events) <> 'array' then v_events := '[]'::jsonb; end if;
  if jsonb_array_length(v_events) > 50 then
    select coalesce(jsonb_agg(e), '[]'::jsonb) into v_events
    from (select e from jsonb_array_elements(v_events) e limit 50) t;
  end if;

  -- A single session never needs more than a few thousand events.
  select event_count into v_existing from public.web_sessions where id = v_sid;
  if v_existing is not null and v_existing >= 3000 then return; end if;

  v_consented := coalesce((s ->> 'consented') = 'true', false);
  v_visitor := case
    when v_consented and (s ->> 'visitor_id') ~ '^[0-9a-f-]{36}$' then s ->> 'visitor_id'
    else null
  end;

  v_ref := left(nullif(s ->> 'referrer', ''), 300);
  v_ref_domain := left(lower(substring(v_ref from '^https?://([^/:?#]+)')), 120);

  select * into v_cls
  from public.wa_classify_traffic(left(s ->> 'utm_source', 100), left(s ->> 'utm_medium', 100), v_ref_domain);

  insert into public.web_sessions (
    id, visitor_id, consented, is_returning,
    host, landing_path, referrer, referrer_domain,
    utm_source, utm_medium, utm_campaign, utm_term, utm_content,
    source, medium, channel,
    device_type, browser, os, language, timezone, viewport_w
  ) values (
    v_sid, v_visitor, v_consented and v_visitor is not null,
    coalesce((s ->> 'is_returning') = 'true', false) and v_visitor is not null,
    left(s ->> 'host', 120), left(s ->> 'landing_path', 300), v_ref, v_ref_domain,
    lower(left(nullif(s ->> 'utm_source', ''), 100)), lower(left(nullif(s ->> 'utm_medium', ''), 100)),
    lower(left(nullif(s ->> 'utm_campaign', ''), 150)), lower(left(nullif(s ->> 'utm_term', ''), 150)),
    lower(left(nullif(s ->> 'utm_content', ''), 150)),
    v_cls.source, v_cls.medium, v_cls.channel,
    left(s ->> 'device_type', 20), left(s ->> 'browser', 40), left(s ->> 'os', 40),
    left(s ->> 'language', 20), left(s ->> 'timezone', 60),
    case when s ->> 'viewport_w' ~ '^\d{2,5}$' then (s ->> 'viewport_w')::int end
  )
  on conflict (id) do update set
    last_seen_at = now(),
    -- Consent can be granted mid-session: upgrade, never downgrade.
    visitor_id = coalesce(public.web_sessions.visitor_id, excluded.visitor_id),
    consented = public.web_sessions.consented or excluded.consented,
    is_returning = public.web_sessions.is_returning or excluded.is_returning;

  with incoming as (
    select
      left(e ->> 'eid', 40) as eid,
      lower(left(e ->> 'type', 40)) as type,
      left(e ->> 'host', 120) as host,
      left(e ->> 'path', 300) as path,
      left(e ->> 'title', 160) as title,
      case when e ->> 'age_ms' ~ '^\d{1,9}$' then least((e ->> 'age_ms')::bigint, 86400000) else 0 end as age_ms,
      case
        when jsonb_typeof(e -> 'props') = 'object' and length((e -> 'props')::text) <= 2000 then e -> 'props'
        else '{}'::jsonb
      end as props
    from jsonb_array_elements(v_events) e
    where jsonb_typeof(e) = 'object'
  ),
  ins as (
    insert into public.web_events (session_id, eid, occurred_at, type, host, path, title, props)
    select v_sid, eid, now() - (age_ms::double precision / 1000) * interval '1 second', type, host, path, title, props
    from incoming
    where coalesce(eid, '') <> '' and type ~ '^[a-z][a-z0-9_]{0,39}$'
    on conflict (session_id, eid) do nothing
    returning type, props
  )
  select
    count(*)::int,
    (count(*) filter (where type = 'pageview'))::int,
    coalesce(sum(case
      when type = 'page_leave' and props ->> 'engaged_ms' ~ '^\d{1,9}$'
        then least((props ->> 'engaged_ms')::bigint, 3600000)
      else 0 end), 0),
    coalesce(max(case
      when type = 'page_leave' and props ->> 'max_scroll' ~ '^\d{1,3}$'
        then least((props ->> 'max_scroll')::int, 100)
      end), 0),
    (array_agg(props ->> 'lead_id') filter (where type = 'form_submit' and props ->> 'lead_id' is not null))[1]
  into v_n, v_pv, v_engaged, v_scroll, v_lead_txt
  from ins;

  -- Only link a lead that really exists (the form submits before reporting).
  if v_lead_txt ~ '^[0-9a-f-]{36}$' then
    select id into v_lead from public.leads where id = v_lead_txt::uuid;
  end if;

  update public.web_sessions set
    pageviews = pageviews + coalesce(v_pv, 0),
    event_count = event_count + coalesce(v_n, 0),
    engaged_ms = engaged_ms + coalesce(v_engaged, 0),
    max_scroll = greatest(max_scroll, coalesce(v_scroll, 0)),
    lead_id = coalesce(lead_id, v_lead)
  where id = v_sid;
end;
$$;

revoke all on function public.track_web_batch(jsonb) from public;
grant execute on function public.track_web_batch(jsonb) to anon, authenticated;


-- 5. Reporting: how are people finding us? ----------------------------------
create or replace function public.web_analytics_acquisition(
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_tz text default 'Africa/Nairobi'
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_from timestamptz := coalesce(p_from, '2000-01-01'::timestamptz);
  v_to timestamptz := coalesce(p_to, now() + interval '1 day');
  v_result jsonb;
begin
  if not public.wa_is_content_team() then
    raise exception 'Not authorised' using errcode = '42501';
  end if;

  with s as (
    select
      ws.*,
      l.id as lid,
      (l.id is not null and l.classification <> 'cold' and not coalesce(l.is_disqualified, false)) as qualified
    from public.web_sessions ws
    left join public.leads l on l.id = ws.lead_id
    where ws.started_at >= v_from and ws.started_at < v_to
  )
  select jsonb_build_object(
    'kpis', (
      select jsonb_build_object(
        'sessions', count(*),
        'visitors', count(distinct coalesce(visitor_id, id::text)),
        'returning_sessions', count(*) filter (where is_returning),
        'leads', count(lid),
        'qualified', count(*) filter (where qualified)
      ) from s
    ),
    'trend', coalesce((
      select jsonb_agg(t order by t.day)
      from (
        select to_char(started_at at time zone p_tz, 'YYYY-MM-DD') as day, count(*) as sessions, count(lid) as leads
        from s group by 1
      ) t
    ), '[]'::jsonb),
    'channels', coalesce((
      select jsonb_agg(c order by c.sessions desc)
      from (
        select channel, count(*) as sessions,
               count(distinct coalesce(visitor_id, id::text)) as visitors,
               count(lid) as leads,
               count(*) filter (where qualified) as qualified
        from s group by channel
      ) c
    ), '[]'::jsonb),
    'sources', coalesce((
      select jsonb_agg(x order by x.sessions desc)
      from (
        select coalesce(source, '(direct)') as source, medium, channel, count(*) as sessions,
               count(lid) as leads, count(*) filter (where qualified) as qualified
        from s group by source, medium, channel
        order by count(*) desc limit 15
      ) x
    ), '[]'::jsonb),
    'campaigns', coalesce((
      select jsonb_agg(x order by x.sessions desc)
      from (
        select utm_campaign as campaign, max(utm_source) as source, count(*) as sessions,
               count(lid) as leads, count(*) filter (where qualified) as qualified
        from s where utm_campaign is not null
        group by utm_campaign
        order by count(*) desc limit 15
      ) x
    ), '[]'::jsonb),
    'referrers', coalesce((
      select jsonb_agg(x order by x.sessions desc)
      from (
        select referrer_domain as domain, channel, count(*) as sessions, count(lid) as leads
        from s where referrer_domain is not null
        group by referrer_domain, channel
        order by count(*) desc limit 10
      ) x
    ), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;


-- 6. Reporting: what are they doing? ----------------------------------------
create or replace function public.web_analytics_behavior(
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_tz text default 'Africa/Nairobi'
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_from timestamptz := coalesce(p_from, '2000-01-01'::timestamptz);
  v_to timestamptz := coalesce(p_to, now() + interval '1 day');
  v_result jsonb;
begin
  if not public.wa_is_content_team() then
    raise exception 'Not authorised' using errcode = '42501';
  end if;

  with ev as (
    select * from public.web_events where occurred_at >= v_from and occurred_at < v_to
  ),
  -- A session counts as "active" (not a bounce) if it did anything beyond
  -- loading a page: clicked, opened the intake form, downloaded, etc.
  active as (
    select distinct session_id from ev
    where type in ('click', 'cta_click', 'outbound', 'download', 'site_form_submit', 'form_view')
  ),
  s as (
    select ws.*,
           (ws.pageviews <= 1 and ws.engaged_ms < 10000 and not exists (select 1 from active a where a.session_id = ws.id)) as bounced,
           l.id as lid,
           (l.id is not null and l.classification <> 'cold' and not coalesce(l.is_disqualified, false)) as qualified
    from public.web_sessions ws
    left join public.leads l on l.id = ws.lead_id
    where ws.started_at >= v_from and ws.started_at < v_to and ws.pageviews > 0
  )
  select jsonb_build_object(
    'kpis', jsonb_build_object(
      'pageviews', (select count(*) from ev where type = 'pageview'),
      'sessions', (select count(*) from s),
      'avg_engaged_seconds', (select coalesce(round(avg(engaged_ms) / 1000.0, 1), 0) from s),
      'pages_per_session', (select coalesce(round(avg(pageviews)::numeric, 2), 0) from s),
      'bounce_rate', (select case when count(*) > 0 then round(100.0 * count(*) filter (where bounced) / count(*), 1) else 0 end from s),
      'avg_scroll', (select coalesce(round(avg(max_scroll)), 0) from s)
    ),
    'trend', coalesce((
      select jsonb_agg(t order by t.day)
      from (
        select to_char(occurred_at at time zone p_tz, 'YYYY-MM-DD') as day, count(*) as pageviews
        from ev where type = 'pageview' group by 1
      ) t
    ), '[]'::jsonb),
    'top_pages', coalesce((
      select jsonb_agg(p order by p.views desc)
      from (
        select host, path,
               count(*) filter (where type = 'pageview') as views,
               count(distinct session_id) filter (where type = 'pageview') as sessions,
               round(coalesce(sum(case when type = 'page_leave' and props ->> 'engaged_ms' ~ '^\d{1,9}$'
                                       then (props ->> 'engaged_ms')::bigint end), 0) / 1000.0
                     / nullif(count(*) filter (where type = 'pageview'), 0), 1) as avg_engaged_seconds,
               round(avg(case when type = 'page_leave' and props ->> 'max_scroll' ~ '^\d{1,3}$'
                              then (props ->> 'max_scroll')::int end)) as avg_scroll
        from ev
        where type in ('pageview', 'page_leave') and path is not null
        group by host, path
        having count(*) filter (where type = 'pageview') > 0
        order by count(*) filter (where type = 'pageview') desc limit 20
      ) p
    ), '[]'::jsonb),
    'landing_pages', coalesce((
      select jsonb_agg(p order by p.sessions desc)
      from (
        select coalesce(landing_path, '/') as path, count(*) as sessions,
               round(100.0 * count(*) filter (where bounced) / count(*), 1) as bounce_rate,
               round(avg(engaged_ms) / 1000.0, 1) as avg_engaged_seconds,
               count(lid) as leads,
               count(*) filter (where qualified) as qualified
        from s group by landing_path
        order by count(*) desc limit 20
      ) p
    ), '[]'::jsonb),
    'clicks', coalesce((
      select jsonb_agg(c order by c.clicks desc)
      from (
        select type, coalesce(props ->> 'label', '(no label)') as label, max(props ->> 'href') as target,
               count(*) as clicks, count(distinct session_id) as sessions
        from ev
        where type in ('click', 'cta_click', 'outbound', 'download', 'site_form_submit')
        group by type, coalesce(props ->> 'label', '(no label)')
        order by count(*) desc limit 20
      ) c
    ), '[]'::jsonb),
    'devices', coalesce((select jsonb_agg(x order by x.sessions desc) from (
      select coalesce(device_type, 'unknown') as name, count(*) as sessions from s group by 1) x), '[]'::jsonb),
    'browsers', coalesce((select jsonb_agg(x order by x.sessions desc) from (
      select coalesce(browser, 'unknown') as name, count(*) as sessions from s group by 1 order by 2 desc limit 6) x), '[]'::jsonb),
    'systems', coalesce((select jsonb_agg(x order by x.sessions desc) from (
      select coalesce(os, 'unknown') as name, count(*) as sessions from s group by 1 order by 2 desc limit 6) x), '[]'::jsonb),
    'timezones', coalesce((select jsonb_agg(x order by x.sessions desc) from (
      select coalesce(timezone, 'unknown') as name, count(*) as sessions from s group by 1 order by 2 desc limit 8) x), '[]'::jsonb),
    'languages', coalesce((select jsonb_agg(x order by x.sessions desc) from (
      select coalesce(nullif(split_part(coalesce(language, ''), '-', 1), ''), 'unknown') as name, count(*) as sessions
      from s group by 1 order by 2 desc limit 6) x), '[]'::jsonb),
    'visitor_mix', (
      select jsonb_build_object(
        'new', count(*) filter (where not is_returning),
        'returning', count(*) filter (where is_returning),
        'consented', count(*) filter (where consented)
      ) from s
    )
  ) into v_result;

  return v_result;
end;
$$;


-- 7. Reporting: are they becoming qualified leads? ---------------------------
-- "Qualified" matches the rest of the app: classification is not cold and the
-- lead is not disqualified (see MarketingAnalytics.jsx).
create or replace function public.web_analytics_conversion(
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_tz text default 'Africa/Nairobi'
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_from timestamptz := coalesce(p_from, '2000-01-01'::timestamptz);
  v_to timestamptz := coalesce(p_to, now() + interval '1 day');
  v_result jsonb;
begin
  if not public.wa_is_content_team() then
    raise exception 'Not authorised' using errcode = '42501';
  end if;

  with s as (
    select ws.*, l.id as lid, l.created_at as lead_created_at, l.classification, l.is_disqualified,
           l.total_score, l.source as lead_source,
           (l.id is not null and l.classification <> 'cold' and not coalesce(l.is_disqualified, false)) as qualified
    from public.web_sessions ws
    left join public.leads l on l.id = ws.lead_id
    where ws.started_at >= v_from and ws.started_at < v_to
  ),
  flags as (
    select e.session_id,
           bool_or(e.type = 'form_view') as f_view,
           bool_or(e.type = 'form_start') as f_start,
           bool_or(e.type = 'form_step_complete' and e.props ->> 'step' = '1') as f_s1,
           bool_or(e.type = 'form_step_complete' and e.props ->> 'step' = '2') as f_s2,
           bool_or(e.type = 'form_slot_selected') as f_slot
    from public.web_events e
    join s on s.id = e.session_id
    where e.type in ('form_view', 'form_start', 'form_step_complete', 'form_slot_selected')
    group by e.session_id
  ),
  -- Each step implies the ones before it, so the funnel can only narrow.
  -- The final step is the real leads row (s.lid), never a client-sent event:
  -- the tracker endpoint is public, so only the database can vouch for a lead.
  cs as (
    select s.*,
           (s.lid is not null) as r_submit,
           (coalesce(f.f_slot, false) or s.lid is not null) as r_slot,
           (coalesce(f.f_s2, false) or coalesce(f.f_slot, false) or s.lid is not null) as r_s2,
           (coalesce(f.f_s1, false) or coalesce(f.f_s2, false) or coalesce(f.f_slot, false) or s.lid is not null) as r_s1,
           (coalesce(f.f_start, false) or coalesce(f.f_s1, false) or coalesce(f.f_s2, false) or coalesce(f.f_slot, false) or s.lid is not null) as r_start,
           (coalesce(f.f_view, false) or coalesce(f.f_start, false) or coalesce(f.f_s1, false) or coalesce(f.f_s2, false) or coalesce(f.f_slot, false) or s.lid is not null) as r_view
    from s left join flags f on f.session_id = s.id
  )
  select jsonb_build_object(
    'funnel', (
      select jsonb_build_object(
        'sessions', count(*),
        'viewed_form', count(*) filter (where r_view),
        'started_form', count(*) filter (where r_start),
        'contact_done', count(*) filter (where r_s1),
        'qualification_done', count(*) filter (where r_s2),
        'picked_slot', count(*) filter (where r_slot),
        'submitted', count(*) filter (where r_submit),
        'qualified', count(*) filter (where qualified)
      ) from cs
    ),
    'steps', coalesce((
      select jsonb_agg(x order by x.step)
      from (
        select e.props ->> 'step' as step,
               count(distinct e.session_id) filter (where e.type = 'form_step_view') as views,
               count(distinct e.session_id) filter (where e.type = 'form_step_complete') as completes,
               round(avg(case when e.type = 'form_step_complete' and e.props ->> 'duration_ms' ~ '^\d{1,9}$'
                              then (e.props ->> 'duration_ms')::bigint end) / 1000.0, 1) as avg_seconds
        from public.web_events e
        join s on s.id = e.session_id
        where e.type in ('form_step_view', 'form_step_complete') and e.props ->> 'step' ~ '^[1-3]$'
        group by e.props ->> 'step'
      ) x
    ), '[]'::jsonb),
    'back_clicks', (
      select count(*) from public.web_events e join s on s.id = e.session_id where e.type = 'form_back'
    ),
    'errors', (
      select count(*) from public.web_events e join s on s.id = e.session_id where e.type = 'form_error'
    ),
    -- Last answer per session per question, so changing your mind counts once.
    'answers', coalesce((
      select jsonb_agg(x order by x.q, x.sessions desc)
      from (
        select q, value, count(*) as sessions
        from (
          select distinct on (e.session_id, e.props ->> 'q')
                 e.props ->> 'q' as q, e.props ->> 'value' as value
          from public.web_events e
          join s on s.id = e.session_id
          where e.type = 'form_answer' and e.props ->> 'q' ~ '^q[1-5]$' and e.props ->> 'value' is not null
          order by e.session_id, e.props ->> 'q', e.occurred_at desc, e.id desc
        ) a
        group by q, value
      ) x
    ), '[]'::jsonb),
    'by_channel', coalesce((
      select jsonb_agg(x order by x.sessions desc)
      from (
        select channel, count(*) as sessions,
               count(*) filter (where r_view) as form_views,
               count(*) filter (where r_start) as form_starts,
               count(lid) as leads,
               count(*) filter (where qualified) as qualified
        from cs group by channel
      ) x
    ), '[]'::jsonb),
    'by_source', coalesce((
      select jsonb_agg(x order by x.sessions desc)
      from (
        select coalesce(source, '(direct)') as source, medium, count(*) as sessions,
               count(*) filter (where r_view) as form_views,
               count(lid) as leads,
               count(*) filter (where qualified) as qualified
        from cs group by source, medium
        order by count(*) desc limit 15
      ) x
    ), '[]'::jsonb),
    'by_campaign', coalesce((
      select jsonb_agg(x order by x.sessions desc)
      from (
        select utm_campaign as campaign, count(*) as sessions,
               count(*) filter (where r_view) as form_views,
               count(lid) as leads,
               count(*) filter (where qualified) as qualified
        from cs where utm_campaign is not null
        group by utm_campaign
        order by count(*) desc limit 15
      ) x
    ), '[]'::jsonb),
    'by_landing', coalesce((
      select jsonb_agg(x order by x.leads desc, x.sessions desc)
      from (
        select coalesce(landing_path, '/') as path, count(*) as sessions,
               count(*) filter (where r_view) as form_views,
               count(lid) as leads,
               count(*) filter (where qualified) as qualified
        from cs group by landing_path
        order by count(lid) desc, count(*) desc limit 15
      ) x
    ), '[]'::jsonb),
    'journeys', coalesce((
      select jsonb_agg(x order by x.at desc)
      from (
        select to_char(lead_created_at at time zone p_tz, 'YYYY-MM-DD HH24:MI') as at,
               classification, is_disqualified, total_score, qualified,
               channel, coalesce(source, '(direct)') as source, lead_source,
               coalesce(landing_path, '/') as landing_path, utm_campaign as campaign,
               pageviews, device_type,
               round(extract(epoch from (lead_created_at - started_at)) / 60.0)::int as minutes_to_convert
        from cs where lid is not null
        order by lead_created_at desc limit 15
      ) x
    ), '[]'::jsonb),
    'timing', (
      select jsonb_build_object(
        'avg_minutes_to_convert', coalesce(round(avg(extract(epoch from (lead_created_at - started_at)) / 60.0)::numeric, 1), 0),
        'avg_pages_before_convert', coalesce(round(avg(pageviews)::numeric, 1), 0)
      ) from cs where lid is not null
    ),
    -- Sanity check: how many leads in the period can be tied to a tracked
    -- session (tracker not installed yet / script blocked => untracked).
    'coverage', (
      select jsonb_build_object(
        'leads_total', count(*),
        'leads_tracked', count(*) filter (where exists (select 1 from public.web_sessions w where w.lead_id = l.id)),
        'qualified_total', count(*) filter (where l.classification <> 'cold' and not coalesce(l.is_disqualified, false))
      )
      from public.leads l where l.created_at >= v_from and l.created_at < v_to
    )
  ) into v_result;

  return v_result;
end;
$$;


-- 8. SEO (Google Search Console) --------------------------------------------
-- Written only by the sm-gsc-sync Edge Function (service role).

-- Site totals per day. Taken from the API with only the "date" dimension, so
-- they include rare queries Google anonymises out of the query-level rows.
create table if not exists public.seo_daily (
  date date primary key,
  clicks integer not null default 0,
  impressions integer not null default 0,
  ctr numeric,
  position numeric,
  synced_at timestamptz default now()
);

create table if not exists public.seo_queries (
  date date not null,
  query text not null,
  page text not null,
  clicks integer not null default 0,
  impressions integer not null default 0,
  position numeric,
  primary key (date, query, page)
);
create index if not exists seo_queries_query_idx on public.seo_queries (query);

create table if not exists public.seo_dimension_daily (
  date date not null,
  dimension text not null check (dimension in ('country', 'device')),
  value text not null,
  clicks integer not null default 0,
  impressions integer not null default 0,
  position numeric,
  primary key (date, dimension, value)
);

alter table public.seo_daily enable row level security;
alter table public.seo_queries enable row level security;
alter table public.seo_dimension_daily enable row level security;

drop policy if exists "Content team can view seo daily" on public.seo_daily;
create policy "Content team can view seo daily"
  on public.seo_daily for select to authenticated using (public.wa_is_content_team());

drop policy if exists "Content team can view seo queries" on public.seo_queries;
create policy "Content team can view seo queries"
  on public.seo_queries for select to authenticated using (public.wa_is_content_team());

drop policy if exists "Content team can view seo dimensions" on public.seo_dimension_daily;
create policy "Content team can view seo dimensions"
  on public.seo_dimension_daily for select to authenticated using (public.wa_is_content_team());

create or replace function public.seo_overview(p_from date default null, p_to date default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_from date := coalesce(p_from, '2000-01-01'::date);
  v_to date := coalesce(p_to, current_date + 1);
  v_result jsonb;
begin
  if not public.wa_is_content_team() then
    raise exception 'Not authorised' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'status', (
      select coalesce(jsonb_object_agg(key, value), '{}'::jsonb)
      from public.system_settings
      where key in ('gsc_site_url', 'gsc_last_sync_at', 'gsc_last_sync_status')
    ),
    'totals', (
      select jsonb_build_object(
        'clicks', coalesce(sum(clicks), 0),
        'impressions', coalesce(sum(impressions), 0),
        'ctr', case when sum(impressions) > 0 then round(sum(clicks)::numeric / sum(impressions), 4) else 0 end,
        'position', case when sum(impressions) > 0 then round((sum(position * impressions) / sum(impressions))::numeric, 1) end,
        'first_date', min(date),
        'last_date', max(date)
      )
      from public.seo_daily where date between v_from and v_to
    ),
    'daily', coalesce((
      select jsonb_agg(d order by d.date)
      from (select date, clicks, impressions from public.seo_daily where date between v_from and v_to) d
    ), '[]'::jsonb),
    'queries', coalesce((
      select jsonb_agg(q order by q.clicks desc, q.impressions desc)
      from (
        select query, sum(clicks)::int as clicks, sum(impressions)::int as impressions,
               round((sum(position * impressions) / nullif(sum(impressions), 0))::numeric, 1) as position,
               case when sum(impressions) > 0 then round(sum(clicks)::numeric / sum(impressions), 4) else 0 end as ctr
        from public.seo_queries where date between v_from and v_to
        group by query
        order by sum(clicks) desc, sum(impressions) desc limit 25
      ) q
    ), '[]'::jsonb),
    -- "Striking distance": already ranking on page 1-2 but not yet winning
    -- the click. These are the cheapest SEO wins.
    'opportunities', coalesce((
      select jsonb_agg(q order by q.impressions desc)
      from (
        select query, sum(clicks)::int as clicks, sum(impressions)::int as impressions,
               round((sum(position * impressions) / nullif(sum(impressions), 0))::numeric, 1) as position,
               case when sum(impressions) > 0 then round(sum(clicks)::numeric / sum(impressions), 4) else 0 end as ctr
        from public.seo_queries where date between v_from and v_to
        group by query
        having sum(impressions) >= 20
           and sum(position * impressions) / nullif(sum(impressions), 0) between 5 and 20
        order by sum(impressions) desc limit 15
      ) q
    ), '[]'::jsonb),
    -- Pages joined to our own tracker: how many organic visits landed here
    -- and how many of those became a lead.
    'pages', coalesce((
      select jsonb_agg(p order by p.clicks desc, p.impressions desc)
      from (
        with pg as (
          select page, sum(clicks)::int as clicks, sum(impressions)::int as impressions,
                 round((sum(position * impressions) / nullif(sum(impressions), 0))::numeric, 1) as position,
                 regexp_replace(regexp_replace(page, '^https?://[^/]+', ''), '(.)/$', '\1') as path
          from public.seo_queries where date between v_from and v_to
          group by page
          order by sum(clicks) desc, sum(impressions) desc limit 25
        ),
        org as (
          select case when length(landing_path) > 1 then rtrim(landing_path, '/') else landing_path end as path,
                 count(*) as sessions, count(lead_id) as leads
          from public.web_sessions
          where channel = 'Organic Search'
            and started_at >= v_from::timestamptz and started_at < (v_to + 1)::timestamptz
          group by 1
        )
        select pg.page, pg.path, pg.clicks, pg.impressions, pg.position,
               coalesce(org.sessions, 0) as organic_sessions, coalesce(org.leads, 0) as organic_leads
        from pg left join org on org.path = pg.path
      ) p
    ), '[]'::jsonb),
    'countries', coalesce((
      select jsonb_agg(x order by x.clicks desc, x.impressions desc)
      from (
        select value as name, sum(clicks)::int as clicks, sum(impressions)::int as impressions
        from public.seo_dimension_daily
        where dimension = 'country' and date between v_from and v_to
        group by value order by sum(clicks) desc, sum(impressions) desc limit 8
      ) x
    ), '[]'::jsonb),
    'devices', coalesce((
      select jsonb_agg(x order by x.clicks desc, x.impressions desc)
      from (
        select value as name, sum(clicks)::int as clicks, sum(impressions)::int as impressions
        from public.seo_dimension_daily
        where dimension = 'device' and date between v_from and v_to
        group by value order by sum(clicks) desc, sum(impressions) desc
      ) x
    ), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;


-- 9. Retention --------------------------------------------------------------
-- Deletes raw sessions (and their events, via cascade) older than N days.
-- Call from pg_cron (see migration-website-analytics-cron.sql). Aggregates
-- are computed live from the raw tables, so keep this at >= the longest
-- period you want to report on.
create or replace function public.wa_purge_old_web_data(p_days integer default 760)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer;
begin
  delete from public.web_sessions where started_at < now() - make_interval(days => p_days);
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

revoke all on function public.wa_purge_old_web_data(integer) from public, anon, authenticated;


-- 10. Grants ------------------------------------------------------------------
revoke all on function public.web_analytics_acquisition(timestamptz, timestamptz, text) from public, anon;
revoke all on function public.web_analytics_behavior(timestamptz, timestamptz, text) from public, anon;
revoke all on function public.web_analytics_conversion(timestamptz, timestamptz, text) from public, anon;
revoke all on function public.seo_overview(date, date) from public, anon;
revoke all on function public.wa_is_content_team() from public, anon;

grant execute on function public.web_analytics_acquisition(timestamptz, timestamptz, text) to authenticated;
grant execute on function public.web_analytics_behavior(timestamptz, timestamptz, text) to authenticated;
grant execute on function public.web_analytics_conversion(timestamptz, timestamptz, text) to authenticated;
grant execute on function public.seo_overview(date, date) to authenticated;
grant execute on function public.wa_is_content_team() to authenticated;

-- Make PostgREST pick up the new functions immediately.
notify pgrst, 'reload schema';
